// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNade(arg1:string):Promise<void>;

export function DeleteVariant(arg1:string):Promise<void>;

export function GetAllNades(arg1:string):Promise<Array<main.Nade>>;

export function GetAllVariants(arg1:string):Promise<Array<main.Variant>>;

export function Greet(arg1:string):Promise<string>;

export function InsertNade(arg1:main.Nade):Promise<string>;

export function InsertVariant(arg1:main.Variant):Promise<string>;

export function UpdateNade(arg1:main.Nade):Promise<void>;

export function UpdateVariant(arg1:main.Variant):Promise<void>;
