// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNade(arg1) {
  return window['go']['main']['App']['DeleteNade'](arg1);
}

export function DeleteVariant(arg1) {
  return window['go']['main']['App']['DeleteVariant'](arg1);
}

export function GetAllNades(arg1) {
  return window['go']['main']['App']['GetAllNades'](arg1);
}

export function GetAllVariants(arg1) {
  return window['go']['main']['App']['GetAllVariants'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function InsertNade(arg1) {
  return window['go']['main']['App']['InsertNade'](arg1);
}

export function InsertVariant(arg1) {
  return window['go']['main']['App']['InsertVariant'](arg1);
}

export function UpdateNade(arg1) {
  return window['go']['main']['App']['UpdateNade'](arg1);
}

export function UpdateVariant(arg1) {
  return window['go']['main']['App']['UpdateVariant'](arg1);
}
